=== migslow/Lenguajes-de-Marcas/Repo/XSD/Ejercicio04/Ejercicio4.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fichas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ficha" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="genero" use="optional" >
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="M"></xs:enumeration>
                                                        <xs:enumeration value="O"></xs:enumeration>
                                                        <xs:enumeration value="F"></xs:enumeration>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="edad">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:integer">
                                            <xs:attribute name="mayor_de_edad" use="optional" type="xs:boolean"></xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="otros">
                                <xs:complexType>
                                    <xs:attribute name="descr" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:integer" use="required"></xs:attribute>
                        <xs:attribute name="idioma" type="xs:string" use="optional" fixed="ES"></xs:attribute>
                        <xs:attribute name="fecha" type="xs:date" use="optional" default="1900-01-01"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== migslow/Lenguajes-de-Marcas/Repo/XSD/Ejercicio04/Ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<fichas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Ejercicio4.xsd" >
   <ficha numero="1" idioma="ES">
      <nombre genero="F">Ana Santos Lorea</nombre>
      <edad>22</edad>
	  <otros descr="Esta es la ficha de Ana"/>
   </ficha>
   <ficha numero="2" fecha="2021-01-25">
      <nombre>Iker Rubio Molino</nombre>
      <edad mayor_de_edad="true">23</edad>
	  <otros descr="Iker tiene la ficha numero 2"/>
   </ficha>
</fichas>
