<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE catalog [
    <!ELEMENT catalog (cd+)>
    <!ELEMENT cd (title, artist, country, company, price, year)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT artist (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT company (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
]>
<catalog>
    <cd>
        <title>Empire Burlesque</title>
        <artist>Bob Dylan</artist>
        <country>USA</country>
        <company>Columbia</company>
        <price>10.90</price>
        <year>1985</year>
    </cd>
    <cd>
        <title>Hide your heart</title>
        <artist>Bonnie Tyler</artist>
        <country>UK</country>
        <company>CBS Records</company>
        <price>9.90</price>
        <year>1988</year>
    </cd>
    <cd>
        <title>Pavarotti Gala Concert</title>
        <artist>Luciano Pavarotti</artist>
        <country>UK</country>
        <company>DECCA</company>
        <price>9.90</price>
        <year>1991</year>
    </cd>
  </catalog>
