=== migslow/Lenguajes-de-Marcas/Repo/XSD/Practica/Practica3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="resultados_encuesta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="encuesta" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="datosAlumno">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="apellidos" type="xs:string" ></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="num">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer" >
                                                <xs:totalDigits value="6"></xs:totalDigits>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="organizacion">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="enunciado" fixed="Valore cada uno de los aspectos de la organizaciÃ³n del viaje, siendo 0 nada satisfecho y 5 muy satisfecho" >
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="idioma">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="ES"></xs:enumeration>
                                                                    <xs:enumeration value="EN"></xs:enumeration>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="viaje">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="[0-5]"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="visitas">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="[0-5]"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="comida">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="[0-5]"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="visitasRealizadas">
                               <xs:complexType>
                                   <xs:sequence>
                                       <xs:element name="info" type="xs:string" minOccurs="0" maxOccurs="unbounded" fixed="Valore los sitios visitados (0 - Nada satisfecho, 5 - Muy satisfecho)"></xs:element>
                                       <xs:element name="visita" minOccurs="3" maxOccurs="3">  
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="sitio">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:IDREF">
                                                                    <xs:pattern value="s1"></xs:pattern>
                                                                    <xs:pattern value="s2"></xs:pattern>
                                                                    <xs:pattern value="s3"></xs:pattern>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                       </xs:element>
                                   </xs:sequence>
                               </xs:complexType>
                            </xs:element>
                            <xs:element name="valoracion_general">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Muy satisfecho"></xs:enumeration>
                                        <xs:enumeration value="Satisfecho"></xs:enumeration>
                                        <xs:enumeration value="Poco satisfecho"></xs:enumeration>
                                        <xs:enumeration value="Nada satisfecho"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="comentario">
                                <xs:complexType mixed="true" >
                                    <xs:choice minOccurs="0" maxOccurs="unbounded" >
                                        <xs:element name="resaltar" type="xs:string"></xs:element>
                                        <xs:element name="colorear">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="color" use="optional" default="rojo" ></xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="marca_temporal" use="required" type="xs:dateTime"/>
                        <xs:attribute name="almacenada_en_bbdd" type="xs:boolean" use="optional" fixed="true"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sitios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sitio" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:ID" use="required" ></xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="estadisticas">
                    <xs:complexType>
                        <xs:attribute name="puntuacion_media">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:fractionDigits value="1"></xs:fractionDigits>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="localizador">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z]{3}([0-9])+([a-z])*[ACE]"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== migslow/Lenguajes-de-Marcas/Repo/XSD/Practica/Practica3.xml
<?xml version="1.0" encoding="UTF-8"?>
<resultados_encuesta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Practica3.xsd">
    <encuesta marca_temporal="2021-09-23T23:56:05" almacenada_en_bbdd="true">
        <datosAlumno num="608500"> 
            <nombre>Pepe</nombre> 
            <apellidos>Romero Pedrasco</apellidos>             
        </datosAlumno> 
        <organizacion> 
            <enunciado idioma="ES">Valore cada uno de los aspectos de la organización del viaje, siendo 0 nada satisfecho y 5 muy satisfecho</enunciado> 
            <viaje>5</viaje>
            <visitas>4</visitas>
            <comida>4</comida>
        </organizacion> 
        <visitasRealizadas>
            <info>Valore los sitios visitados (0 - Nada satisfecho, 5 - Muy satisfecho)</info>
            <visita sitio="s1">5</visita>
            <visita sitio="s3">3</visita>
            <visita sitio="s2">4</visita>
        </visitasRealizadas>
        <valoracion_general>Muy satisfecho</valoracion_general> 
        <comentario>Repetiría <resaltar>sin duda</resaltar>, lo mejor del <colorear color="verde">viaje</colorear> fué la visita al <colorear>superordenador</colorear></comentario>
    </encuesta> 
    <encuesta marca_temporal="2021-10-23T08:50:34">
        <datosAlumno num="57684"> 
            <nombre>Noelia</nombre> 
            <apellidos>Piedrafita Soler</apellidos>             
        </datosAlumno> 
        <organizacion>             
            <comida>3</comida>    
            <enunciado>Valore cada uno de los aspectos de la organización del viaje, siendo 0 nada satisfecho y 5 muy satisfecho</enunciado>             
            <viaje>4</viaje>
            <visitas>5</visitas>            
        </organizacion> 
        <visitasRealizadas>
            <visita sitio="s2">4</visita>
            <visita sitio="s1">5</visita>
            <visita sitio="s3">3</visita>
        </visitasRealizadas>
        <valoracion_general>Satisfecho</valoracion_general> 
        <comentario>Fue un viaje <colorear color="naranja">muy interesante</colorear> pero la <resaltar>comida</resaltar> podría mejorar. La visita al <resaltar>museo</resaltar> me aburrió un poco.</comentario>
    </encuesta>
    <sitios>
        <sitio id="s1">Mare Nostrum</sitio>
        <sitio id="s2">Park Güell</sitio>
        <sitio id="s3">Museo de arte</sitio>
    </sitios>
    <estadisticas puntuacion_media="4.3"/>
    <localizador>AHG3524asgkgC</localizador>
</resultados_encuesta>
