=== migslow/Lenguajes-de-Marcas/Repo/XSD/Ejercicio11/Ejercicio11.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="discos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grupo" minOccurs="0" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="miembro" minOccurs="0" maxOccurs="4">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nacionalidad" minOccurs="0" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nom" type="xs:ID" ></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="disco" minOccurs="0" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="interprete">
                                <xs:complexType>
                                    <xs:attribute name="nom" type="xs:IDREFS" ></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="titulo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="discografica" default="CBS" minOccurs="0" maxOccurs="unbounded" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                        <xs:enumeration value="Sony"></xs:enumeration>
                                        <xs:enumeration value="CBS"></xs:enumeration>
                                        <xs:enumeration value="SIRE"></xs:enumeration>
                                        <xs:enumeration value="OTRAS"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="anio" minOccurs="0" maxOccurs="10" >
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:integer">
                                            <xs:attribute name="mes">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:maxLength value="50"></xs:maxLength>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="stock">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:maxInclusive value="200"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="precio">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:fractionDigits value="2"></xs:fractionDigits>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== migslow/Lenguajes-de-Marcas/Repo/XSD/Ejercicio11/Ejercicio11.xml
<?xml version="1.0" encoding="UTF-8"?>
<discos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio11.xsd">
  <grupo nom="muse">
    <nombre>MUSE</nombre>
    <miembro>Matthew Bellamy</miembro>
    <miembro>Dominic Howard</miembro>
    <miembro>Chris Wolstenholme</miembro>
    <nacionalidad>Alemania</nacionalidad>
  </grupo>
  <grupo nom="feeder">
    <nombre>FEEDER</nombre>
    <miembro>Grant Nicholas</miembro>
    <miembro>Taka Hirose</miembro>
    <miembro>Jon Henry Lee</miembro>
  </grupo>
  <grupo nom="nvnud">
    <nombre>No vendo ni un disco</nombre>
    <miembro>Marta</miembro>
    <miembro>Ramon</miembro>
    <miembro>Pedro</miembro>
  </grupo>
  <disco precio="12.80">
    <interprete nom="muse"/>
    <titulo>Showbiz</titulo>
    <discografica>Sony</discografica>
    <anio>2000</anio>
    <stock>20</stock>
  </disco>
  <disco precio="19.90">
    <interprete nom="feeder"/>
    <titulo>Echo Park</titulo>
    <discografica>Sony</discografica>
    <anio>1980</anio>
    <stock>5</stock>
  </disco>
  <disco precio="15.50">
    <interprete nom="muse"/>
    <titulo>Origin of symmetry</titulo>
    <discografica>SIRE</discografica>
    <anio mes="enero">2007</anio>
    <stock>20</stock>
  </disco>
  <disco precio="13.20">
    <interprete nom="feeder"/>
    <titulo>Comfort In Sound</titulo>
    <anio>2010</anio>
    <stock>27</stock>
  </disco>
  <disco precio="4.90">
    <interprete nom="nvnud"/>
    <titulo>Esto suena realmente mal</titulo>
    <anio>2011</anio>
    <stock>200</stock>
  </disco>
</discos>
